import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.min.css";
import { useState, useRef } from 'react';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const letters = Array.from({ length: 26 }, (_, i) => String.fromCharCode(97 + i));
  const [wordList, setWordList] = useState([]);
  const [filteredWordList, setFilteredWordList] = useState([]);
  const [searchInp, setSearchInp] = useState(0);

  const onSearchClick = async () => {
    const response = await fetch('/api/search?searchType=singleValueNumeric&scoreToMatch=' + searchInp);
    const data = await response.json();
    setWordList(data);
    setFilteredWordList(data);
  };

  const onSearchFilter = async (letter: string) => {
    setFilteredWordList(wordList.filter((word: string) => word.startsWith(letter)))
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className="container col-sm-6 ">
          <div className="row ">
            <div className="input-group">
              <input onChange={e => setSearchInp(Number(e.target.value))} type="search" className="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
              <button type="button" onClick={() => onSearchClick()} className="btn btn-outline-primary">search</button>
            </div>
          </div>
          <br />
          <div className="row">
            {letters.map(letter => (
              <button key={letter} onClick={() => onSearchFilter(letter)} className="btn ms-1 mb-1 col-sm-1 btn-primary">{letter}</button>
            ))}
          </div>
          <div className="overflow-auto vh-100 p-3 bg-light" >
            {filteredWordList.map((word, index) => (
              <p className='lh-1' key={index}>{word}</p>
            ))}
          </div>
        </div>
      </main>
    </>
  )
}
